### ISSUE TITLE
Display Scenarios assigned to the user

### ISSUE THREAD

**Issue by djos192** [UoaWDCC/VPS#110]
Get the required scenario data for the player assigned the task on MongoDB, and relay it to the dashboard the player sees upon logging into the application

**Comment by arnard76** [comment]
On double clicking an assigned scenario, open new tab for user (student) to start playing the game (url is same as the url for sharing). 

Can't edit or delete an assigned scenario so don't show those sidebar actions when an assigned scenario is selected. 

@djos192 lmk if this is going in the wrong direction 🙂
