### ISSUE TITLE
[VPS-138] The 'Create New Scene' button has a giant **+** in the middle of it

### ISSUE THREAD

**Issue by JordanBlenn** [UoaWDCC/VPS#138]
**Description:**

**AS A:** User
**I WANT:** The create scene button to have a + in the middle of it
**SO THAT:** It looks more like a create scene button

**AC's:**
1) When editing a scene, the create scene button has a giant **+** in the centre of it, with a max height of 80% the height of the component and a max width of 80% the width of the component.

**Technical Discussion:**

**Other Notes:**
Originally we also had AC 2 as part of this user story, but after discussion it has been deemed out of scope and will be fixed in a future issue. 
2) The **+** dynamically resizes as the window size changes, always restricted 80% width/height of the minimum of the height or width of the component.
To be fixed in #146

**Comment by wjin-lee** [comment]
We should maybe change the second acceptance criteria?
Currently, the size of the scene elements (boxes) are relative to screen width at 20%. (I.e. it will ALWAYS show ~5). See case B in screenshot.
We could instead make this a fixed length or defined in `rem` and decoupling it from screen size. See case A.
![image](https://github.com/UoaWDCC/VPS/assets/100455176/c432900c-a145-4bfb-9414-f98936192665)

**Comment by JordanBlenn** [comment]
> We should maybe change the second acceptance criteria? Currently, the size of the scene elements (boxes) are relative to screen width at 20%. (I.e. it will ALWAYS show ~5). See case B in screenshot. We could instead make this a fixed length or defined in `rem` and decoupling it from screen size. See case A. ![image](https://private-user-images.githubusercontent.com/100455176/317115381-c432900c-a145-4bfb-9414-f98936192665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMDM4MTIsIm5iZiI6MTcxMjAwMzUxMiwicGF0aCI6Ii8xMDA0NTUxNzYvMzE3MTE1MzgxLWM0MzI5MDBjLWExNDUtNGJmYi05NDE0LWY5ODkzNjE5MjY2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQyMDMxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjVkYzMzYjc1Y2NlNDk1NDU1NWI1OGZjMjAxZjM4ODYwODk1MDU3ZDNkMjQ3ZWUzZjIyZGNiOWZmOGFhMGJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Plhew_-hB1-g8XR4hGX-larRRxM-MWC_c6gH88652kU)

Good point - is this worth covering in this story or pulling out of scope into another one? I would personally prefer to make another story dealing with this, but keen to hear your feedback as well @wjin-lee. 
I'll change the second AC as necessary after your feedback.

**Comment by wjin-lee** [comment]
> > We should maybe change the second acceptance criteria? Currently, the size of the scene elements (boxes) are relative to screen width at 20%. (I.e. it will ALWAYS show ~5). See case B in screenshot. We could instead make this a fixed length or defined in `rem` and decoupling it from screen size. See case A. ![image](https://private-user-images.githubusercontent.com/100455176/317115381-c432900c-a145-4bfb-9414-f98936192665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMDM4MTIsIm5iZiI6MTcxMjAwMzUxMiwicGF0aCI6Ii8xMDA0NTUxNzYvMzE3MTE1MzgxLWM0MzI5MDBjLWExNDUtNGJmYi05NDE0LWY5ODkzNjE5MjY2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQyMDMxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjVkYzMzYjc1Y2NlNDk1NDU1NWI1OGZjMjAxZjM4ODYwODk1MDU3ZDNkMjQ3ZWUzZjIyZGNiOWZmOGFhMGJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Plhew_-hB1-g8XR4hGX-larRRxM-MWC_c6gH88652kU)
> 
> Good point - is this worth covering in this story or pulling out of scope into another one? I would personally prefer to make another story dealing with this, but keen to hear your feedback as well @wjin-lee. I'll change the second AC as necessary after your feedback.

Yep I agree - we should probably merge the current PR, and make another story for fixed-length containers.
