### ISSUE TITLE
[VPS-154](2)(0.5) Uploading a CSV file creates appropriate groups and assigns roles (No UI)

### ISSUE THREAD

**Issue by JordanBlenn** [UoaWDCC/VPS#154]
**Description:**

**AS A:** Staff member creating scenarios
**I WANT:** to be able to upload a csv file containing group information
**SO THAT:** Groups are created with roles that people can play through

**AC's:**
1) A .csv file of a specific and exact format [email, name, group number, role], if uploaded to the system:
- Creates Group entries in the database 

**Technical Discussion:**
- The group entry/object contains a list of users that defines their roles (including name and email)

**Comment by wjin-lee** [comment]
During development - just make a dummy `<input>` with the type of file. 
See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file

**Comment by JordanBlenn** [comment]
Does the current implementation of CSV uploading allow a new CSV to be uploaded overriding the previous one? If so (and I think it should in case the wrong file is uploaded), it is important that roles are stored in such a way that if the name of a role is changed it doesn't impact other features we have yet to implement (such as assigning roles to specific scenes etc). We possibly could force people to always use the same number of roles (i.e. if they initially upload a CSV file with 3 roles they have to always use 3 roles no matter what for this scenario) if we warn them when the first upload a CSV. Most of this implementation can be done in a future story but this is something to keep in mind for overall design considering some future stories which rely on the list of roles determined by the CSV file.

Alternatively, we have the user input roles separately and store them there, and uploading a CSV file requires the same roles as headings or it doesn't work? 

Keen to hear your thoughts @Kot6603 @laibatool792 @wjin-lee

**Comment by JordanBlenn** [comment]
> Does the current implementation of CSV uploading allow a new CSV to be uploaded overriding the previous one? If so (and I think it should in case the wrong file is uploaded), it is important that roles are stored in such a way that if the name of a role is changed it doesn't impact other features we have yet to implement (such as assigning roles to specific scenes etc). We possibly could force people to always use the same number of roles (i.e. if they initially upload a CSV file with 3 roles they have to always use 3 roles no matter what for this scenario) if we warn them when the first upload a CSV. Most of this implementation can be done in a future story but this is something to keep in mind for overall design considering some future stories which rely on the list of roles determined by the CSV file.
> 
> Alternatively, we have the user input roles separately and store them there, and uploading a CSV file requires the same roles as headings or it doesn't work?
> 
> Keen to hear your thoughts [@Kot6603](https://github.com/Kot6603) [@laibatool792](https://github.com/laibatool792) [@wjin-lee](https://github.com/wjin-lee)

I'm currently thinking along the lines of having another story to implement a manage roles feature (#176), but we'd probably need a list of acceptable roles (which can be changed as we go) stored in the database, right? Or am I dumb and does this easily already exist?

**Comment by wjin-lee** [comment]
> Does the current implementation of CSV uploading allow a new CSV to be uploaded overriding the previous one? If so (and I think it should in case the wrong file is uploaded), it is important that roles are stored in such a way that if the name of a role is changed it doesn't impact other features we have yet to implement (such as assigning roles to specific scenes etc). We possibly could force people to always use the same number of roles (i.e. if they initially upload a CSV file with 3 roles they have to always use 3 roles no matter what for this scenario) if we warn them when the first upload a CSV. Most of this implementation can be done in a future story but this is something to keep in mind for overall design considering some future stories which rely on the list of roles determined by the CSV file.
> 
> Alternatively, we have the user input roles separately and store them there, and uploading a CSV file requires the same roles as headings or it doesn't work?
> 
> Keen to hear your thoughts @Kot6603 @laibatool792 @wjin-lee

Good catch on this one - my initial thinking so far is as follows:

_Given that a CSV and its corresponding roles already exist:_
If a new CSV was uploaded:
- All group progress is reset (because they are brand-new groups!)
- If a role that previously existed no longer exists, all references are simply considered "invalid" and database references remain in the invalid state.
  - Functionally, this means we simply show a "INVALID" label in the UI if we detect any fields that were previouslly set to the now non-existant role.
  - Scenes that were previously limited to that will internally still hold those values, but obviously since nobody holds that role any more they will remain inaccessible until the scene permissions are fixed.

THIS MEANS:
- We _(really)_ should to revise the schema and CSV upload such that we maintain a list of roles. This list would simply be updated every CSV upload, since we need to synthesise a list of roles anyways _somewhere_ during the CSV validation process.

**Comment by JordanBlenn** [comment]
Based on irl discussion 6/5/2024: Role list is stored within the scenario and added in this story
