### ISSUE TITLE
[VPS-155](0.5) Creating the UI for a Manage Groups view

### ISSUE THREAD

**Issue by JordanBlenn** [UoaWDCC/VPS#155]
**Description:**

**AS A:** Staff member creating scenarios
**I WANT:** To be able to see a "Manage Groups" view
**SO THAT:** I can add groups to play this scenario

**AC's:**
1) As a staff member, I can click a "Manage Groups" Button on the top of a scenario view
2) When clicked, this navigates to a new screen containing:
- An Upload CSV button
- A table displaying the groups
- A "Download Play Links" button (this functionality is implemented in a later user story TBD)
3) This new screen is at the link -----.wdcc.co.nz/{scenarioId}/manage-groups

**Technical Discussion:**
-  the functionality of the Upload CSV button is dependent on #154 
- Blocked by #156 (design for this)

**Comment by codecreator127** [comment]
Made a figma for the Manage Groups UI



![Image](https://github.com/UoaWDCC/VPS/assets/120153300/ed5a489c-9e29-4d6e-8878-5df9c98ebdf3)



https://www.figma.com/file/YLNft7DgzQNLfoi2dSNl8l/Manage-Groups-Page?type=design&node-id=0%3A1&mode=design&t=37rdh4yfoHaoh0WB-1
