### ISSUE TITLE
[VPS-156] A design for the Manage Groups is created

### ISSUE THREAD

**Issue by JordanBlenn** [UoaWDCC/VPS#156]
**Description:**

**AS A:** VPS developer
**I WANT:** to have a clear design for what the "Manage Groups" page should look like
**SO THAT:** I can implement the frontend next sprint

**AC's:**
1) The design for the Manage Groups page is created and approved with respect to specifications in #155 

**Technical Discussion:**
- Blocks coding in #155

**Comment by codecreator127** [comment]
Made a figma for the Manage Groups UI



![Image](https://github.com/UoaWDCC/VPS/assets/120153300/ed5a489c-9e29-4d6e-8878-5df9c98ebdf3)



https://www.figma.com/file/YLNft7DgzQNLfoi2dSNl8l/Manage-Groups-Page?type=design&node-id=0%3A1&mode=design&t=37rdh4yfoHaoh0WB-1

**Comment by JordanBlenn** [comment]
Looks good to me! @wjin-lee is this sort of what you were envisioning?

**Comment by wjin-lee** [comment]
Yep - the only comment would be to make the table take up the entire width of the page.

It seems weird to me to have a bounded table - we can definitely leave some space at the top if we suspect filtering, etc. But as for lateral width I think it's better to take up max width. What do you guys think?

**Comment by JordanBlenn** [comment]
Yep that sounds good to me

**Comment by codecreator127** [comment]
@wjin-lee Yep, max width table is fine with me. It was just an arbitrary design choice to have it bounded haha
