### ISSUE TITLE
[VPS-157](1) Tracking the last scenario viewed

### ISSUE THREAD

**Issue by JordanBlenn** [UoaWDCC/VPS#157]
**Description:**

**AS A:** User
**I WANT:** to keep track of my last scenario
**SO THAT:** if I reload the page I don't end up back at the start/my group members jump to the same place I have gotten up to

**AC's:**
1) The last visited scene for the group is kept track of 
2) If I reload the page or access on another device, it takes me to the last visited scene (stored)
3) If another group member accesses the scene, it takes me to the last visited scene **of the entire group**.
4) If 2 people on separate devices both choose different pathways at the same time, then only the first one is taken (race condition handling)

**Technical Discussion:**
One way to implement AC4 would be to have an API that every client (frontend) needs to call before traversing to the next scene. This could be the same API call it makes to record the path taken.

To this API endpoint, the client reports the current scene, and the next scene it wants to traverse to. The API endpoint then compares if the current scene recorded in the request matches the one on the server. If so, it will add it to the end of the path and return a successful return code. (do this the entire read + write with transactions).

**Comment by harbassan** [comment]
could possibly look into long polling for a 'real time' updating of the active scene when another member changes it.
