### ISSUE TITLE
[VPS-159] There is a design for Scene Permissions

### ISSUE THREAD

**Issue by JordanBlenn** [UoaWDCC/VPS#159]
**Description:**

**AS A:** VPS dev
**I WANT:** designs made for Scene permission access
**SO THAT:** I can easily implement them in the UI

**AC's:**
1) Designs are made as follows:
- A Page showing "Your role does not have access to this scene. Please wait for your {allowed role} to play through this part of the scenario." 
- A tag on each scene clearly showing what role(s) have access to that scene (if any)

**Technical Discussion:**

**Comment by wjin-lee** [comment]
![Image](https://github.com/UoaWDCC/VPS/assets/100455176/3b9eb683-b88f-4f9d-8668-daca52d19c29)

**Comment by JordanBlenn** [comment]
👍

**Comment by JordanBlenn** [comment]
@wjin-lee @jacobmathew105 do we have a design for in edit mode, showing which roles have access to what scenes? Either something like a list somewhere on the edit page with all roles able to access it, or even a "Manage permissions" Button which pulls up a list of all permissions that can view the scene (with the ability to edit these at will) - like a modal.

**Comment by wjin-lee** [comment]
> @wjin-lee @jacobmathew105 do we have a design for in edit mode, showing which roles have access to what scenes? Either something like a list somewhere on the edit page with all roles able to access it, or even a "Manage permissions" Button which pulls up a list of all permissions that can view the scene (with the ability to edit these at will) - like a modal. Or do you reckon we move this to another User Story (i.e. for next sprint) instead?

I reckon that should be next sprint where we pair design + implementation.

Design could be literally just a multiselect drop down in edit mode

**Comment by JordanBlenn** [comment]
Sounds good
