### ISSUE TITLE
Create prototype dashboard

### ISSUE THREAD

**Issue by nickykay98** [UoaWDCC/VPS#28]
## Issue Description

Create a dashboard for lecturers to see information about their students like their play time, scores on scenarios etc (and other metrics that could be generated from students playing the scenarios).

## User Story

"As a lecturer, I would like to be able to see how well my students are performing in the scenarios I create."

## MVP

Figma prototype/s of what the dashboard would look like, including
- how information about students and scenarios are displayed
- what kind of summary statistics can be shown (e.g. percentage of students that have completed a scenario)
- how a lecturer could filter by scenario or by student (e.g. to see which students have completed what scenarios)

## Tasks

- [x] Create shareable Figma file
- [x] Task 2
- [x] Task 3

**Comment by nickykay98** [comment]
@DamonGreenhalgh @retinfai feel free to add any other details that I might have missed and don't hesitate to reach out to me/@Harshal-D and contact each other! 😊

**Comment by retinfai** [comment]
@DamonGreenhalgh What's you're email I'll share a figma workspace with you

**Comment by DamonGreenhalgh** [comment]
damonligreenhalgh@gmail.com

**Comment by nickykay98** [comment]
@retinfai Not familiar with the NZPMC project but I presume you'd need to clone and run the backend repo as well

**Comment by retinfai** [comment]
> @retinfai Not familiar with the NZPMC project but I presume you'd need to clone and run the backend repo as well

Oh right of course aha. Part of the set up is the Firebase key – we wouldn't have access to that would we? It might be more trouble than its worth tbh. I could just look at some online examples

**Comment by nickykay98** [comment]
> > @retinfai Not familiar with the NZPMC project but I presume you'd need to clone and run the backend repo as well
> 
> Oh right of course aha. Part of the set up is the Firebase key – we wouldn't have access to that would we? It might be more trouble than its worth tbh. I could just look at some online examples

Yeah I don't think they'd be willing to give that to us haha... I could ask for some screenshots though

**Comment by retinfai** [comment]
Yes please that'd be really helpful

**Comment by nickykay98** [comment]
@DamonGreenhalgh @retinfai I've uploaded screenshots provided by @jameszu (Project Director) here: https://drive.google.com/drive/u/1/folders/19OzRbUlV5ctYSWbRj1JvWVpAoDlKJXe5

Keep an eye out, more may be uploaded soon.

**Comment by DamonGreenhalgh** [comment]
Hey! here is a link to the Figma file,
https://www.figma.com/file/GoKwVs9nuQWrep4LpLoz6O/Dashboard?node-id=0%3A1

**Comment by retinfai** [comment]
Yo @DamonGreenhalgh! I think it's worth mulling over the design of the dashboard before we think about implementing anything. I'm still a bit iffy about the user experience of the whole thing. And also, I was thinking we should probably revise our design so that it encompasses **only** analytical data that this team will implement. What are your thoughts? 

I'm actually tending towards wanting to put the dashboard on the back burner and focus on implementing the actual metrics first.

**Comment by DamonGreenhalgh** [comment]
@retinfai Yeah, I will go back and clean up the figma prototype. I will assume the metrics that are used in the prototype are possible to attain. But I agree with you, implementing the actual metrics first will help with the design of the dashboard.

**Comment by retinfai** [comment]
Sweet, I like you're design so don't make too many drastic changes aha

**Comment by nickykay98** [comment]
@retinfai @DamonGreenhalgh Please merge changes (if any) made on this branch into main and pass the unit tests, then we'll open up new stories for you to work on for sprint 4

**Comment by Harshal-D** [comment]
@DamonGreenhalgh @retinfai The link for the Figma doesn't seem to be working, if you guys could also just post another link or even post some screenshots of the Figma design here (as comments) that would also work. Thanks!

**Comment by retinfai** [comment]
@nickykay98 I can't speak for @DamonGreenhalgh, but I did not make any changes – also I don't think a new branch was created, so nothing to merge.

**Comment by retinfai** [comment]
@Harshal-D Sweet! Here are the screenshots we had designed so far.
![Screen Shot 2022-08-04 at 7 15 12 PM](https://user-images.githubusercontent.com/79831813/182786835-cab606b1-536c-45f5-b024-1bbc233a0f31.png)
![Screen Shot 2022-08-04 at 7 15 57 PM](https://user-images.githubusercontent.com/79831813/182786981-bc6c6833-fd57-40fb-bff5-5830b64b283d.png)
![Screen Shot 2022-08-04 at 7 16 16 PM](https://user-images.githubusercontent.com/79831813/182787057-3d4da90b-afa7-47e8-9323-465c1a3c01e1.png)
![Screen Shot 2022-08-04 at 7 16 33 PM](https://user-images.githubusercontent.com/79831813/182787106-ba84dea7-0dd7-4296-95f7-a23f0fa4cd00.png)

**Comment by nickykay98** [comment]
@retinfai @DamonGreenhalgh Uploaded the screenshots above here so that they don't get lost in the issue: https://drive.google.com/drive/u/1/folders/1SagbpzECNgFhbIi_Uq_dvsNcnEfv5zl9

Will close this issue now and assign you to new ones for sprint 4
