### ISSUE TITLE
Store timer data and other potential metrics into MongoDB

### ISSUE THREAD

**Issue by nickykay98** [UoaWDCC/VPS#30]
## Issue Description

Store metrics associated with a user and scenario such as the amount of time they played it for into MongoDB

## User Story

"As a lecturer, I'd like to be able to have the app save info about my students when they play the scenarios I create such as which students have and haven't played my scenarios, and how long did they take to play a scenario"

## MVP

Database fields showing what users played which scenarios and how long they played them for, and allowing for other metrics to be stored too down the line

## Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by nickykay98** [comment]
@KW781 @jfen445 feel free to add any other details that I might have missed and don't hesitate to reach out to me/@Harshal-D and contact each other! 😊 Please refer to our meeting minutes for more details: https://docs.google.com/document/d/12zVyaj8VlxgzpDsclpp5i6_1j1ORm3zQVtTEurwiEaI/edit#

**Comment by KW781** [comment]
Hey, sorry if this has been covered before, but I was wondering how we could get access to the MongoDB database? Just so that we know how the data is stored and whatnot.

**Comment by nickykay98** [comment]
@KW781 All good! Just use these login details: https://docs.google.com/spreadsheets/d/1_kc8wmavF17BlgqJXJpPG4_cJ4JODjz1Ikw-WCkajwg/edit#gid=0&range=A5

**Comment by KW781** [comment]
Thanks! One more thing, I didn't actually work on the timer functionality in the last sprint, so I was wondering where the timer data was collected. Is it collected in the frontend and sent to the backend? Or is the timing performed in the backend?

**Comment by nickykay98** [comment]
> Thanks! One more thing, I didn't actually work on the timer functionality in the last sprint, so I was wondering where the timer data was collected. Is it collected in the frontend and sent to the backend? Or is the timing performed in the backend?

@jfen445 @aadenmann @lia-arroyo @mlai962?

**Comment by jfen445** [comment]
> Thanks! One more thing, I didn't actually work on the timer functionality in the last sprint, so I was wondering where the timer data was collected. Is it collected in the frontend and sent to the backend? Or is the timing performed in the backend?

i worked on the timer functionality last sprint, timer duration is stored in mongo, perhaps we can find some time to work on this together?

**Comment by aing810** [comment]
@nickykay98 Yup ill be happy to.

**Comment by nickykay98** [comment]
@aadenmann regarding your question (in terms of only allowing lecturers and TA to access the dashboard, couldn't we store in the DB the list of all TAs and lecturers and just check if the user is on that list and give them permission?)

I think the concern generally expressed was security as I don't believe it's best practice to do role management with a DB that only stores assets like image files and scenario objects... but I might be wrong and/or you guys might have learned something different in SE, it's certainly one way to go about allowing conditional access!

**Comment by KW781** [comment]
@jfen445 I'd be happy to find a time to work with you, maybe we can chat on Discord to work out a time?

**Comment by DamonGreenhalgh** [comment]
Hey! below is a link to the Figma file.
https://www.figma.com/file/GoKwVs9nuQWrep4LpLoz6O/Dashboard?node-id=0%3A1

**Comment by nickykay98** [comment]
@KW781 @jfen445 @aadenmann  Please merge changes (if any) made on this branch into main and pass the unit tests, then we'll open up new stories for you to work on for sprint 4

**Comment by nickykay98** [comment]
> @KW781 @jfen445 @aadenmann Please merge changes (if any) made on this branch into main and pass the unit tests, then we'll open up new stories for you to work on for sprint 4

Will just pick on someone lol - @aadenmann did you want to open up a PR and assign @KW781 @jfen445 to review it?

**Comment by aadenmann** [comment]
> > @KW781 @jfen445 @aadenmann Please merge changes (if any) made on this branch into main and pass the unit tests, then we'll open up new stories for you to work on for sprint 4
> 
> Will just pick on someone lol - @aadenmann did you want to open up a PR and assign @KW781 @jfen445 to review it?

Yup can do
