### ISSUE TITLE
Investigate H5P component integration

### ISSUE THREAD

**Issue by nickykay98** [UoaWDCC/VPS#35]
## Issue Description

Investigate how to integrate H5P components into the app, specifically:
- How to get data out of components
- How to customise components
- How lecturer could drag and drop components during scene creation
- How to know when an activity e.g. quiz in a component has been completed by a user

Refer to these links to get started: 
- https://h5p.org/documentation/x-api
- https://h5p.org/documentation/for-authors/analyzing-results-and-answers
- https://h5p.org/node/309384
- https://h5p.org/node/468797 

## User Story

"As a student, I would like to be able to interact with H5P components and the content that the lecturer created within them as I'm playing a scenario"

"As a lecturer, I'd like to be able to insert H5P components into my scenes and scenarios and edit them with my own content within the VPS app, if possible"

## MVP

This is a spike story to assess the feasibility and cost of integrating H5P components in future sprints...  so while there is no definitive MVP, you could try to add in as much functionality within the app as you can to demo at the end of the sprint e.g. letting a user select and insert H5P components while editing a scene

Notes within the shared Drive about what you find out would also be very helpful!

## Tasks

Describe the tasks in this story.

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by nickykay98** [comment]
@jfen445 Sorry for the delay, and thanks for volunteering to look into this, really appreciate it! @Harshal-D tagging to keep you in the loop

Please note, a branch has already been created: https://github.com/UoaWDCC/VPS/tree/VPS-035/investigate-h5p-component-integration

**Comment by jfen445** [comment]
- https://socket.dev/npm/package/@lumieducation/h5p-html-exporter
- https://github.com/Lumieducation/H5P-Nodejs-library

A few links in which I was investing. Was not able to intergrate the h5p components into react. Thought it would be component based but that does not seem like that case to me.

**Comment by nickykay98** [comment]
@jfen445 Thanks for that! Will close this issue after we concluded at today's meeting we won't pursue this further, assigned you to the timer functionality issue :) - https://github.com/UoaWDCC/VPS/issues/34
