### ISSUE TITLE
Create backend dashboard endpoint

### ISSUE THREAD

**Issue by nickykay98** [UoaWDCC/VPS#36]
## Issue Description

Create endpoint/s on the backend that feeds data from MongoDB into the dashboard on the frontend. This is so that when the dashboard is accessed by a lecturer, the latest information about their students (names, email addresses etc) and metrics about their performance on scenarios are displayed on the dashboard

See minutes from [3/8/22](https://docs.google.com/document/d/1tK8Goe7VbGD-C0zOAQzgCRt4Zg3RCA6aZ1Z6QVdvDkQ/edit?pli=1#) and [27/7/22](https://docs.google.com/document/d/12zVyaj8VlxgzpDsclpp5i6_1j1ORm3zQVtTEurwiEaI/edit#) for more details

## User Story

User stories to help describe what the functionality is meant to be able to achieve.

## MVP

The exact data to be gotten is probably a consideration for future sprints as the dashboard is fleshed out and the H5P components are investigated... but for now, successfully getting back user info and any data about their that's already in the database (or even just dummy data like Ray mentioned at the meeting last week) should qualify as an MVP!

## Tasks

Describe the tasks in this story.

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by nickykay98** [comment]
@aadenmann Please add any info above if you want, apologies for there not being much to work with at the start - reach out to us or Ray for any clarification 😊 @Harshal-D Tagging to keep you in the loop

Note, a branch has already been created: https://github.com/UoaWDCC/VPS/tree/VPS-036/create-backend-dashboard-endpoint

**Comment by aadenmann** [comment]
@nickykay98 @Harshal-D Managed to get the endpoint to work thanks to @DamonGreenhalgh, now we are just wondering what kind of information would be store at the dashboard collection, currently we are going through what/where information would be stored for the graphs and in most case you would store that information in either scenario or scenes collection.

**Comment by nickykay98** [comment]
Great, thanks for the update! Yeah, the database schema will get more complicated what with all the info about users and their play metrics needing to be stored... ER diagrams might help - feel free to share any plans you and @DamonGreenhalgh come up with so me/@Harshal-D/@Ray-F can take a look, otherwise we'll discuss this on Wednesday

**Comment by nickykay98** [comment]
@aadenmann Will close this issue now so that you and Damon can just work on the dashboard branch with Matthew and Alfred (assigned you to it now) - see next steps on meeting minutes: https://docs.google.com/document/d/1neECFP0l_P6iPdUjTK8zj2mKnl4gjYnc96gTF1mcVW8/edit#bookmark=id.c99e286gi2uh
