### ISSUE TITLE
As a user, I want to see character text in speech bubbles, so that I know which character is talking

### ISSUE THREAD

**Issue by djos192** [UoaWDCC/VPS#52]
**Tasks in this user story**

- [x] #57 
- [x] #58 
- [x] #59 
- [x] #60 
- [x] #61  

**Requirements**

Currently, there are only text boxes to show character dialogue. We want this changed to a speech bubble so it:

1. Looks more aesthetic
2. Easily identify which character is talking

**Comment by arnard76** [comment]
Task #57 and Task #59 rely on each other. I.e. no point having a button that does nothing AND choosing speech box only possible using the button. 

Task #57 isn't on the project board anymore so I should include both tasks in the code for Task #59?

**Comment by arnard76** [comment]
Full feature completed and functioning  🙃

https://vps-dev.wdcc.co.nz/
