### ISSUE TITLE
As a user, I don't want to see the Faculty of Medical Sciences logo and theme, so all my friends in other departments don't feel excluded

### ISSUE THREAD

**Issue by Ryuna001** [UoaWDCC/VPS#56]
**Task list**

- [x] #50 

**Description**

- Currently, the theme of VPS is based on the Faculty of Medical Sciences logo and colours. We want to change this to University of Auckland theme. The client wants VPS to be used by everyone at UoA.

**Comment by arnard76** [comment]
Completed and working at 👇

https://vps-dev.wdcc.co.nz/
