### ISSUE TITLE
Choose a speech bubble theme to add to simulator

### ISSUE THREAD

**Issue by Ryuna001** [UoaWDCC/VPS#58]
**User Story**

- [ ] #52 

**Description**

Choose and add a speech bubble theme for the simulator.

**Comment by arnard76** [comment]
Sorry if its already been mentioned, but does "theme" in this task only refer to an additional button in scene editor?
like this 👇
![image](https://user-images.githubusercontent.com/78939786/234725815-0ec9aa60-8b8c-47de-aa5f-b884bb654b2e.png)

Is there something else that is included in "theme" here?

**Comment by arnard76** [comment]
There is [another task](https://github.com/UoaWDCC/VPS/issues/57) for the speech icon (button) so I'm guessing "theme" refers to something else about the speech box?

**Comment by arnard76** [comment]
Never mind, I think I understand. This task is to allow user to add a new speech box.

**Comment by Ryuna001** [comment]
Speech bubble theme means that the text box looks like a speech bubble.



![Image](https://github.com/UoaWDCC/VPS/assets/127585171/5b75acb0-d568-46fe-99ec-e0494ad4c98d)

**Comment by arnard76** [comment]
This my progress so far

![image](https://github.com/UoaWDCC/VPS/assets/78939786/4efa60e0-e63a-436f-8fb9-a1f074e18530)

**Comment by arnard76** [comment]
Currently, the arrow/pointing thingy only points upwards. I am not sure if being able to adjust direction of the pointing thingy is a part of this task or #60.
