### ISSUE TITLE
Add a pop up screen when time is running out

### ISSUE THREAD

**Issue by djos192** [UoaWDCC/VPS#62]
**User Story**

- [ ] #49 

**Description**

- Add small pop-up screen which is non-intrusive when there are 30 seconds left in the scene

**Comment by j-enn-y** [comment]
![image](https://user-images.githubusercontent.com/127184310/235834800-f2a0a057-c761-4617-a262-dbe9735d257c.png)
Pop up added when there are 30 seconds left in the scene
