### ISSUE TITLE
Add double click functionality to the scenario page

### ISSUE THREAD

**Issue by Ryuna001** [UoaWDCC/VPS#67]
**User Story**

- [ ] #65 

**Description**

- Add a mouse event which navigates to the scene the user has double clicked to
- Basically accessing the edit function but by a mouse click

**Comment by arnard76** [comment]
What should happen when user double clicks the name of the scenario?

![image](https://github.com/UoaWDCC/VPS/assets/78939786/c7f2dc43-9e4e-4b27-8ba9-ef4dd3d94be2)
