### ISSUE TITLE
Add labels in toolbar

### ISSUE THREAD

**Issue by nickykay98** [UoaWDCC/VPS#7]
**User Story**
"As a user I'd like to clearly interpret what each tool in the toolbar is"

Add labels next to the icons for the scene editing toolbar.
EG: "Add Image" or "Image", "Add button" or "Button" to make it clear what each tool is.

**Comment by lia-arroyo** [comment]
Hey! I added the toolbar labels as seen below: 

![image](https://user-images.githubusercontent.com/94775011/167291119-45098e14-1ec7-4010-ba5a-a6f4eb5a48ac.png)

I've pushed my changes onto this branch: https://github.com/UoaWDCC/VPS/tree/VPS-007/toolbar-labels. If everything looks all good, should I start a pull request?

**Comment by nickykay98** [comment]
Looks great! Please open a PR 😊
