### ISSUE TITLE
Bug with error when reading status on dev website

### ISSUE THREAD

**Issue by djos192** [UoaWDCC/VPS#78]
Error shown in the frontend and backend crudHooks.js in reading the status, check console on https://vps-uoa.netlify.app/

**Comment by arnard76** [comment]
1st bug:

![image](https://user-images.githubusercontent.com/78939786/235833041-10650fc4-48bd-4bb8-bffe-f5e9f6d49b3a.png)

**Comment by arnard76** [comment]
2nd bug:

![image](https://user-images.githubusercontent.com/78939786/235833097-f8521526-bea8-46b7-8d43-c4cc14e57493.png)

**Comment by arnard76** [comment]
@djos192 can I tackle both in this issue?

**Comment by arnard76** [comment]
This is closed but backend hasn't deployed so 1st error still occurring on deployed site.
