### ISSUE TITLE
Create Help/Info button on Homepage and Edit Screens

### ISSUE THREAD

**Issue by Harshal-D** [UoaWDCC/VPS#9]
[**User Story**]
"As a user I'd like to to view instructions and guidelines to on how to use the app from wherever I am."

Add an Help/Info popup on the homescreen and scene editing screen which allows the user to view a guide on how to use the app. 

Homepage help button to allow users to have a quick look at how to use and understand the app. This should also be accessible from the scene editor (maybe with a small (?) or something), so users can always know how to work the app.

**Comment by DamonGreenhalgh** [comment]
Hey! @nickykay98 @Harshal-D @jfen445 
Here are a couple of previews of what the app looks like with the help button and modal.

> Home

![image](https://user-images.githubusercontent.com/59471444/169471802-2d03bd00-42ae-4599-89cc-1c70fd0df38b.png)

> Help popup (done by Josh) 

![image](https://user-images.githubusercontent.com/59471444/169472259-08231619-ce8b-4416-b146-bbac79fda827.png) 

> Scene selection 

![image](https://user-images.githubusercontent.com/59471444/169473159-f42517d0-b446-4416-ad21-3dc20ad6ea7d.png)

> Scene editor 

![image](https://user-images.githubusercontent.com/59471444/169473480-d1d28584-4c40-4ead-9262-a16b13289997.png) 

Feel free to give us some feedback before we open up a pull request.
Thanks!

**Comment by nickykay98** [comment]
Looks great! 

Would be awesome if you added like a "Help"/"How To" label next to the button in the main menu? Whatever you guys think works best 😊

**Comment by DamonGreenhalgh** [comment]
Added text and changed the button style. Now matches the back button styling.

> Home

![image](https://user-images.githubusercontent.com/59471444/169520340-460de4a3-f005-404d-91b4-e606e600b782.png)

> Scene selection

![image](https://user-images.githubusercontent.com/59471444/169520375-739c987c-694a-4c10-82a8-f33a16b647f8.png)

**Comment by nickykay98** [comment]
Looks great! I will merge soon

**Comment by Harshal-D** [comment]
Awesome work Damon, looks great!
